[package]
name = "glfmn-io"
version = "0.1.0"
authors = ["Gwen Lofman <Gwen@Lofman.io>"]
description = "WASM components of glfmn.io"
edition = "2018"
repository = "https://github.com/glfmn/glfmn.io"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
